create extension if not exists vector;

create table if not exists analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  patient_label text not null,
  score integer not null,
  eligible boolean not null,
  trial_name text,
  summary text,
  result jsonb
);

-- Optional next-step vector table for protocol chunks.
create table if not exists protocol_chunks (
  id bigint generated by default as identity primary key,
  trial_id bigint,
  chunk_text text not null,
  page integer,
  embedding vector(1536)
);

alter table analyses enable row level security;
alter table protocol_chunks enable row level security;

create policy "demo read analyses" on analyses for select using (true);
create policy "demo insert analyses" on analyses for insert with check (true);
