-- ==============================================================================
-- NexusClin Supabase Schema & pgvector Configuration (Zephoria 2K26 PS-02)
-- ==============================================================================

-- 1. Enable the pgvector extension for semantic clinical evidence retrieval
create extension if not exists vector;

-- 2. Patient cohort analysis results table
create table if not exists analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  patient_label text not null,
  score integer not null check (score >= 0 and score <= 100),
  eligible boolean not null,
  overall_status text not null default 'NOT_ELIGIBLE',
  trial_name text,
  summary text,
  result jsonb not null
);

-- 3. Page-aware protocol chunks table with vector embeddings
create table if not exists protocol_chunks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  trial_name text not null,
  page integer check (page > 0),
  section text,
  chunk_text text not null,
  embedding vector(1536)
);

-- 4. Vector index for fast cosine distance matching
create index if not exists protocol_chunks_embedding_idx
  on protocol_chunks
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- 5. RPC function for semantic evidence retrieval using pgvector cosine distance
create or replace function match_protocol_chunks (
  query_embedding vector(1536),
  match_threshold float default 0.25,
  match_count int default 8,
  filter_trial_name text default null
)
returns table (
  id bigint,
  trial_name text,
  page integer,
  section text,
  chunk_text text,
  similarity float
)
language sql stable
as $$
  select
    protocol_chunks.id,
    protocol_chunks.trial_name,
    protocol_chunks.page,
    protocol_chunks.section,
    protocol_chunks.chunk_text,
    1 - (protocol_chunks.embedding <=> query_embedding) as similarity
  from protocol_chunks
  where
    (filter_trial_name is null or protocol_chunks.trial_name = filter_trial_name)
    and (1 - (protocol_chunks.embedding <=> query_embedding)) > match_threshold
  order by similarity desc
  limit match_count;
$$;

-- 6. Row Level Security (RLS) policies
alter table analyses enable row level security;
alter table protocol_chunks enable row level security;

-- Drop obsolete or overly permissive demo policies if present
drop policy if exists "demo read analyses" on analyses;
drop policy if exists "demo insert analyses" on analyses;
drop policy if exists "Allow read analyses" on analyses;
drop policy if exists "Allow validated insert analyses" on analyses;
drop policy if exists "Allow read protocol_chunks" on protocol_chunks;
drop policy if exists "Allow insert protocol_chunks" on protocol_chunks;

-- Controlled read access for clinical cohort reviews
create policy "Allow read analyses"
  on analyses for select
  using (true);

-- Validated insertion policy: prevent arbitrary or corrupt data injection
create policy "Allow validated insert analyses"
  on analyses for insert
  with check (
    patient_label is not null
    and score >= 0
    and score <= 100
  );

-- Read access for protocol chunks during semantic retrieval
create policy "Allow read protocol_chunks"
  on protocol_chunks for select
  using (true);

-- Validated insert for protocol chunks
create policy "Allow insert protocol_chunks"
  on protocol_chunks for insert
  with check (
    trial_name is not null
    and length(chunk_text) > 0
  );
